Controllers/CuentaBancariaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using pc2_antaurco.Data;
using pc2_antaurco.Models;
using pc2_antaurco.ViewModel;

namespace pc2_antaurco.Controllers
{

    public class CuentaBancariaController : Controller
    {
        private readonly ILogger<CuentaBancariaController> _logger;
        private readonly ApplicationDbContext _context;

        public CuentaBancariaController(ILogger<CuentaBancariaController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            var cuentas = from o in _context.DataCuentaBancaria select o;
            
            var viewModel = new CuentaBancariaViewModel
            {
                FormCuentaBancaria = new CuentaBancaria(), 
                ListarCuentaBancaria = cuentas.ToList() 
            };

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Registrar(CuentaBancariaViewModel viewModel)
        {
            if (viewModel.FormCuentaBancaria.Id == 0)
            {
                _context.Add(viewModel.FormCuentaBancaria);
                TempData["Message"] = "Excelente ingreso una nueva cuenta :D";
            }

            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Controllers/ListarCuentasController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using pc2_antaurco.Data;
using pc2_antaurco.ViewModel;
using pc2_antaurco.Models;

namespace pc2_antaurco.Controllers
{
    public class ListarCuentasController : Controller
    {
        private readonly ILogger<ListarCuentasController> _logger;
        private readonly ApplicationDbContext _context;

        public ListarCuentasController(ILogger<ListarCuentasController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        // Acción que carga la vista principal con el listado de cuentas
        public IActionResult Index()
        {
            // Obtiene todas las cuentas bancarias de la base de datos
            var cuentas = _context.DataCuentaBancaria.ToList();

            // Crea el ViewModel con las cuentas obtenidas
            var viewModel = new CuentaBancariaViewModel
            {
                ListarCuentaBancaria = cuentas // Lista de cuentas para la tabla
            };

            return View(viewModel); // Retorna la vista con el modelo
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BankCrom</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/pc2_antaurco.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJZELhqVttOtyfGe7rMPP6LN1q1DoIvS2GuQ&s" alt="BankCore" class="img-fluid" style="max-height: 50px;" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidad</a>
                         </li>   
                        <partial name="_MenuAdminPartial" />
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer  white-text">
        <div class="container">
            &copy; 2024 - BankCrom - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacidad</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_MenuAdminPartial.cshtml
@using Microsoft.AspNetCore.Identity;
@using System.Collections.Generic;

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@if (SignInManager.IsSignedIn(User)){
    IdentityUser myidentity = await Task.Run(() => UserManager.GetUserAsync(User));
    var roles = await Task.Run(() => UserManager.GetRolesAsync(myidentity));

    @if(roles.Contains("admin") ){
        <li class="nav-item">
            <a class="nav-link text-dark bi bi-cart" asp-area="" asp-controller="ListarCuentas" asp-action="Index">Listar Cuentas</a>
        </li>

    }else{
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="CuentaBancaria" asp-action="Index">Registrar Cuenta</a>
        </li>
    } 
}